# Generated by Django 5.0.6 on 2024-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.CharField(max_length=3)),
                ('atomic_number', models.IntegerField()),
            ],
        ),
    ]
