# Generated by Django 5.0.6 on 2024-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='symbol',
            field=models.CharField(max_length=2),
        ),
    ]
