import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // title: "Create Next App",
  title: "Next.js 14 + Django 5",
  description: "UI for restaurant menus & period table elements",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-[70%] h-[90vh] my-0 mx-auto p-5 bg-[#999] rounded-lg shadow-md">
          {children}
        </main>
      </body>
    </html>
  );
}
